import pytest

from projects.models import Project


pytestmark = pytest.mark.django_db


def test_user_str_and_full_name(user):
    assert "user@test.com" in str(user)
    assert user.get_full_name() == "Тест Пользователь"


def test_user_avatar_is_autogenerated(user):
    assert user.avatar
    assert user.avatar.name.endswith(".png")


def test_project_defaults(user):
    project = Project.objects.create(name="X", owner=user)
    assert project.status == Project.STATUS_OPEN
    assert project.created_at is not None


def test_owned_and_participated_related_names(user, project):
    assert list(user.owned_projects.all()) == [project]
    assert list(user.participated_projects.all()) == [project]


def test_favorites_related_name(user, project):
    user.favorites.add(project)
    assert list(project.interested_users.all()) == [user]
